### ISSUE TITLE
Autocomplete Field to Select Group Does Not Appear to Work

### ISSUE THREAD

**Issue by mkinnan** [signalpoint/og#3]
The Group Reference field for my _event_ content type does not do anything when typing in letters to the field to select the _group_ node. Console log gives this error:

`GET: http://websitename.com/?q=undefined&title=car`

where _car_ is the word I typed into the autocomplete field.

**Comment by signalpoint** [comment]
@mkinnan What widget type are you using on your field? I know this worked at one point, but I think I might have botched it with all the updates to entityreference.js the other day, it's probably a quick-ish fix, as I was just "forwarding" og widgets off to entity reference.

**Comment by mkinnan** [comment]
@signalpoint The widget type is set to **autocomplete**.

**Comment by mkinnan** [comment]
Appears to be fixed in the lasted release of OG and entity reference.
